name: PHP Package
on:
  push:
  pull_request:
  workflow_call:
jobs:
  format-check:
    name: Check PSR12 Standarts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
      - run: composer install
        shell: bash
      - run: composer format:check
        shell: bash
  tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug3
      - run: composer install
        shell: bash
      - run: composer test
        shell: bash
